# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{Scribd_fu}
  s.version = "2.0.6"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Matt Darby"]
  s.date = %q{2009-11-23}
  s.description = %q{A Rails gem that streamlines interactions with the Scribd service}
  s.email = %q{matt@matt-darby.com}
  s.extra_rdoc_files = [
    "README.textile"
  ]
  s.files = [
    "MIT-LICENSE",
     "README.textile",
     "VERSION",
     "generators/scribd_fu/scribd_fu_generator.rb",
     "generators/scribd_fu/templates/scribd_fu.yml",
     "init.rb",
     "lib/scribd_fu.rb",
     "lib/scribd_fu/attachment_fu.rb",
     "lib/scribd_fu/paperclip.rb",
     "scribd_fu.gemspec",
     "spec/database.yml",
     "spec/scribd_fu.yml",
     "spec/scribd_fu_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/mdarby/scribd_fu}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{A Rails gem that streamlines interactions with the Scribd service}
  s.test_files = [
    "spec/scribd_fu_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

